<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/assets/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $_SESSION['name'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->tweetCount ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->followingCount ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->followersCount ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form method="get" action="/quem_seguir">
								<div class="input-group mb-3">
									<input type="text" class="form-control" placeholder="Quem você está procurando?" name="pesquisarPor">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<? foreach($this->view->users as $user){?>
			<div class="row mb-2">
				<div class="col">
				
					<div class="card">
						<div class="card-body">
							
								<div class="row">
									<div class="col-md-6">
										<?= $user['nome'] ?>
									</div>
							
									<div class="col-md-6 d-flex justify-content-end">
										<div>
											<? if($user['seguindo_sn']==0){?>
												<a href="/acao?acao=seguir&id_usuario=<?=$user['id']?>&pesquisarPor=<?=$_GET['pesquisarPor']?>" class="btn btn-success">Seguir</a>
											<? } ?>
											<? if($user['seguindo_sn']==1){?>	
												<a href="/acao?acao=deixar_de_seguir&id_usuario=<?=$user['id']?>&pesquisarPor=<?=$_GET['pesquisarPor']?>" class="btn btn-danger">Deixar de seguir</a>
											<?}?>
										</div>
									</div>
								</div>
							
						</div>
					</div>
				
				</div>
			</div>
			<? } ?>

		</div>
	</div>
</div>